# Generated by Django 3.2 on 2022-03-29 14:59

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(db_column='category_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('friendlyname', models.CharField(blank=True, db_column='friendlyName', max_length=45, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(db_column='Product_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('friendlyname', models.CharField(db_column='friendlyName', max_length=45)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('sku', models.CharField(max_length=254, unique=True)),
                ('has_sizes', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('X-large', 'X-large')], max_length=350, null=True)),
                ('colors', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('red', 'Red'), ('Pink', 'Pink'), ('Green', 'Green'), ('Blue', 'Blue'), ('Grey', 'Grey'), ('Black', 'Black'), ('White', 'White'), ('Brown', 'Brown')], max_length=350, null=True)),
            ],
            options={
                'db_table': 'Products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subcategories',
            fields=[
                ('subcategory_id', models.AutoField(db_column='subcategory_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('friendly_name', models.CharField(blank=True, max_length=45, null=True)),
                ('category', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('dogs', 'dogs'), ('cats', 'cats'), ('birds', 'birds'), ('rodents', 'rodents')], max_length=350, null=True)),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
                'db_table': 'SUBCATEGORIES',
                'managed': False,
            },
        ),
    ]
